// <auto-generated />
using System;
using KR4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KR4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511173858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KR4.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("VisitCost")
                        .HasColumnType("numeric");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Главная площадь России, сердце Москвы",
                            History = "Красная площадь существует с конца XV века. На ней расположены Кремль, Собор Василия Блаженного, Мавзолей Ленина и ГУМ. Площадь является символом России и внесена в список Всемирного наследия ЮНЕСКО.",
                            Name = "Красная площадь",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Moscow_Red_Square.jpg/1280px-Moscow_Red_Square.jpg",
                            WorkingHours = "Круглосуточно"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Крупнейший музей русского изобразительного искусства",
                            History = "Галерея основана в 1856 году купцом Павлом Третьяковым. В коллекции хранится более 180 000 произведений искусства — живопись, графика, скульптура, декоративно-прикладное искусство с XI по XX век.",
                            Name = "Третьяковская галерея",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Tretyakov_gallery.JPG/1280px-Tretyakov_gallery.JPG",
                            VisitCost = 500m,
                            WorkingHours = "Вт–Вс: 10:00–18:00, Чт–Пт: 10:00–21:00"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Один из крупнейших и наиболее значимых художественных и культурно-исторических музеев мира",
                            History = "Музей основан в 1764 году Екатериной Великой. Коллекция насчитывает около 3 миллионов экспонатов. Главный корпус — Зимний дворец — был официальной резиденцией российских императоров.",
                            Name = "Эрмитаж",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Hermitage_museum_2007.jpg/1280px-Hermitage_museum_2007.jpg",
                            VisitCost = 600m,
                            WorkingHours = "Вт–Вс: 11:00–19:00, Ср: 11:00–21:00"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "Дворцово-парковый ансамбль, «Русский Версаль»",
                            History = "Петергоф основан Петром I в начале XVIII века. Знаменит своей уникальной системой фонтанов, которая работает без насосов — только за счёт естественного перепада высот. Внесён в список Всемирного наследия ЮНЕСКО.",
                            Name = "Петергоф",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Grand_Cascade_Peterhof.jpg/1280px-Grand_Cascade_Peterhof.jpg",
                            VisitCost = 1000m,
                            WorkingHours = "Пн–Вс: 09:00–20:00 (сезонно)"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Уникальный памятник истории и архитектуры, объект Всемирного наследия ЮНЕСКО",
                            History = "Кремль является древнейшей частью Казани. На его территории расположены мечеть Кул-Шариф, Благовещенский собор и другие исторические постройки. Включён в список Всемирного наследия ЮНЕСКО в 2000 году.",
                            Name = "Казанский Кремль",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Kazan_Kremlin_towers.jpg/1280px-Kazan_Kremlin_towers.jpg",
                            VisitCost = 300m,
                            WorkingHours = "Пн–Вс: 09:00–18:00"
                        });
                });

            modelBuilder.Entity("KR4.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoatOfArmsUrl")
                        .HasColumnType("text");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoatOfArmsUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Coat_of_Arms_of_Moscow.svg/240px-Coat_of_Arms_of_Moscow.svg.png",
                            History = "Москва — столица России, один из крупнейших городов мира. Первое упоминание о Москве относится к 1147 году. Город был основан князем Юрием Долгоруким и с тех пор прошёл долгий путь от небольшого поселения до мегаполиса мирового значения.",
                            Name = "Москва",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Moscow_July_2011-7a.jpg/1280px-Moscow_July_2011-7a.jpg",
                            Population = 12506468,
                            Region = "Центральный федеральный округ"
                        },
                        new
                        {
                            Id = 2,
                            CoatOfArmsUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Coat_of_Arms_of_Saint_Petersburg_%282003%29.svg/240px-Coat_of_Arms_of_Saint_Petersburg_%282003%29.svg.png",
                            History = "Санкт-Петербург основан Петром I в 1703 году и был столицей Российской империи более 200 лет. Город знаменит своей уникальной архитектурой, многочисленными музеями и культурными традициями. Его нередко называют «Северной Венецией» из-за множества рек и каналов.",
                            Name = "Санкт-Петербург",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Palace_Bridge_SPB.jpg/1280px-Palace_Bridge_SPB.jpg",
                            Population = 5601911,
                            Region = "Северо-Западный федеральный округ"
                        },
                        new
                        {
                            Id = 3,
                            CoatOfArmsUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Coat_of_arms_of_Kazan.svg/240px-Coat_of_arms_of_Kazan.svg.png",
                            History = "Казань — столица Республики Татарстан, один из крупнейших городов России. Город был основан около 1000 лет назад и является крупным культурным, научным и спортивным центром страны. В 2013 году здесь прошла Универсиада, а в 2018 — матчи Чемпионата мира по футболу.",
                            Name = "Казань",
                            PhotoUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Kazan_Kremlin_from_across_Kazanka_river.jpg/1280px-Kazan_Kremlin_from_across_Kazanka_river.jpg",
                            Population = 1257391,
                            Region = "Приволжский федеральный округ"
                        });
                });

            modelBuilder.Entity("KR4.Models.Attraction", b =>
                {
                    b.HasOne("KR4.Models.City", "City")
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("KR4.Models.City", b =>
                {
                    b.Navigation("Attractions");
                });
#pragma warning restore 612, 618
        }
    }
}
