// <auto-generated />
using System;
using KR4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KR4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511204023_UpdateImagesAndChurch")]
    partial class UpdateImagesAndChurch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KR4.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("VisitCost")
                        .HasColumnType("numeric");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Главная площадь России, сердце Москвы",
                            History = "Красная площадь существует с конца XV века. На ней расположены Кремль, Собор Василия Блаженного, Мавзолей Ленина и ГУМ. Площадь является символом России и внесена в список Всемирного наследия ЮНЕСКО.",
                            Name = "Красная площадь",
                            PhotoUrl = "/images/Moscow_red_square_attarction.jpg",
                            WorkingHours = "Круглосуточно"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Главный кафедральный собор Русской православной церкви",
                            History = "Храм Христа Спасителя был возведён в XIX веке в память о победе в Отечественной войне 1812 года. В советское время взорван, а в 1990-х годах воссоздан заново. Является одним из символов Москвы и крупнейшим православным храмом России.",
                            Name = "Храм Христа Спасителя",
                            PhotoUrl = "/images/Moscow_church_attarction.jpg",
                            WorkingHours = "Пн–Вс: 10:00–17:00"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Один из крупнейших и наиболее значимых художественных и культурно-исторических музеев мира",
                            History = "Музей основан в 1764 году Екатериной Великой. Коллекция насчитывает около 3 миллионов экспонатов. Главный корпус — Зимний дворец — был официальной резиденцией российских императоров.",
                            Name = "Эрмитаж",
                            PhotoUrl = "/images/Ermitage_attraction.jpg",
                            VisitCost = 600m,
                            WorkingHours = "Вт–Вс: 11:00–19:00, Ср: 11:00–21:00"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "Дворцово-парковый ансамбль, «Русский Версаль»",
                            History = "Петергоф основан Петром I в начале XVIII века. Знаменит своей уникальной системой фонтанов, которая работает без насосов — только за счёт естественного перепада высот. Внесён в список Всемирного наследия ЮНЕСКО.",
                            Name = "Петергоф",
                            PhotoUrl = "/images/Peterhof_attraction.jpg",
                            VisitCost = 1000m,
                            WorkingHours = "Пн–Вс: 09:00–20:00 (сезонно)"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Уникальный памятник истории и архитектуры, объект Всемирного наследия ЮНЕСКО",
                            History = "Кремль является древнейшей частью Казани. На его территории расположены мечеть Кул-Шариф, Благовещенский собор и другие исторические постройки. Включён в список Всемирного наследия ЮНЕСКО в 2000 году.",
                            Name = "Казанский Кремль",
                            PhotoUrl = "/images/Kazan_attraction.jpg",
                            VisitCost = 300m,
                            WorkingHours = "Пн–Вс: 09:00–18:00"
                        });
                });

            modelBuilder.Entity("KR4.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoatOfArmsUrl")
                        .HasColumnType("text");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoatOfArmsUrl = "/images/Coat_of_arms_of_Moscow.svg.png",
                            History = "Москва — столица России, один из крупнейших городов мира. Первое упоминание о Москве относится к 1147 году. Город был основан князем Юрием Долгоруким и с тех пор прошёл долгий путь от небольшого поселения до мегаполиса мирового значения.",
                            Name = "Москва",
                            PhotoUrl = "/images/Moscow_dash_pic.jpg",
                            Population = 12506468,
                            Region = "Центральный федеральный округ"
                        },
                        new
                        {
                            Id = 2,
                            CoatOfArmsUrl = "/images/Coat_of_arms_of_Saint_Petersburg_(2003).svg.png",
                            History = "Санкт-Петербург основан Петром I в 1703 году и был столицей Российской империи более 200 лет. Город знаменит своей уникальной архитектурой, многочисленными музеями и культурными традициями. Его нередко называют «Северной Венецией» из-за множества рек и каналов.",
                            Name = "Санкт-Петербург",
                            PhotoUrl = "/images/SPB_dash.jpg",
                            Population = 5601911,
                            Region = "Северо-Западный федеральный округ"
                        },
                        new
                        {
                            Id = 3,
                            CoatOfArmsUrl = "/images/Coat_of_Arms_of_Kazan_(Tatarstan).svg.png",
                            History = "Казань — столица Республики Татарстан, один из крупнейших городов России. Город был основан около 1000 лет назад и является крупным культурным, научным и спортивным центром страны. В 2013 году здесь прошла Универсиада, а в 2018 — матчи Чемпионата мира по футболу.",
                            Name = "Казань",
                            PhotoUrl = "/images/Kazan_dash.jpg",
                            Population = 1257391,
                            Region = "Приволжский федеральный округ"
                        });
                });

            modelBuilder.Entity("KR4.Models.Attraction", b =>
                {
                    b.HasOne("KR4.Models.City", "City")
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("KR4.Models.City", b =>
                {
                    b.Navigation("Attractions");
                });
#pragma warning restore 612, 618
        }
    }
}
