// <auto-generated />
using System;
using KR5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KR5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KR5.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MinimalStock")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinimalStock = 100m,
                            Name = "Сталь",
                            Quantity = 500m,
                            UnitOfMeasure = "кг"
                        },
                        new
                        {
                            Id = 2,
                            MinimalStock = 50m,
                            Name = "Резина",
                            Quantity = 200m,
                            UnitOfMeasure = "кг"
                        },
                        new
                        {
                            Id = 3,
                            MinimalStock = 100m,
                            Name = "Пластик",
                            Quantity = 80m,
                            UnitOfMeasure = "кг"
                        },
                        new
                        {
                            Id = 4,
                            MinimalStock = 75m,
                            Name = "Алюминий",
                            Quantity = 350m,
                            UnitOfMeasure = "кг"
                        });
                });

            modelBuilder.Entity("KR5.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinimalStock")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductionTimePerUnit")
                        .HasColumnType("integer");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Механика",
                            Description = "Стальная шестерня для редуктора",
                            MinimalStock = 50,
                            Name = "Шестерня А",
                            ProductionTimePerUnit = 30,
                            Specifications = "{\"диаметр\":\"120мм\",\"зубья\":24}"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Корпуса",
                            Description = "Пластиковый корпус для электроники",
                            MinimalStock = 30,
                            Name = "Корпус Б",
                            ProductionTimePerUnit = 20,
                            Specifications = "{\"размер\":\"200x150x80мм\",\"цвет\":\"черный\"}"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Уплотнители",
                            Description = "Резиновая прокладка уплотнительная",
                            MinimalStock = 200,
                            Name = "Прокладка В",
                            ProductionTimePerUnit = 5,
                            Specifications = "{\"диаметр\":\"50мм\",\"толщина\":\"5мм\"}"
                        });
                });

            modelBuilder.Entity("KR5.Models.ProductMaterial", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityNeeded")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ProductMaterials");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            MaterialId = 1,
                            QuantityNeeded = 2.5m
                        },
                        new
                        {
                            ProductId = 1,
                            MaterialId = 4,
                            QuantityNeeded = 0.5m
                        },
                        new
                        {
                            ProductId = 2,
                            MaterialId = 3,
                            QuantityNeeded = 0.8m
                        },
                        new
                        {
                            ProductId = 3,
                            MaterialId = 2,
                            QuantityNeeded = 0.2m
                        });
                });

            modelBuilder.Entity("KR5.Models.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentWorkOrderId")
                        .HasColumnType("integer");

                    b.Property<float>("EfficiencyFactor")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductionLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EfficiencyFactor = 1f,
                            Name = "Линия №1",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            EfficiencyFactor = 1.2f,
                            Name = "Линия №2",
                            Status = "Stopped"
                        },
                        new
                        {
                            Id = 3,
                            EfficiencyFactor = 0.8f,
                            Name = "Линия №3",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("KR5.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EstimatedEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MaterialsConsumed")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductionLineId")
                        .HasColumnType("integer");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstimatedEndDate = new DateTime(2026, 5, 12, 0, 58, 50, 702, DateTimeKind.Utc).AddTicks(8230),
                            MaterialsConsumed = true,
                            ProductId = 1,
                            ProductionLineId = 1,
                            Progress = 45,
                            Quantity = 10,
                            StartDate = new DateTime(2026, 5, 10, 20, 58, 50, 702, DateTimeKind.Utc).AddTicks(8224),
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 2,
                            EstimatedEndDate = new DateTime(2026, 5, 12, 3, 58, 50, 702, DateTimeKind.Utc).AddTicks(8236),
                            MaterialsConsumed = false,
                            ProductId = 2,
                            Progress = 0,
                            Quantity = 20,
                            StartDate = new DateTime(2026, 5, 11, 20, 58, 50, 702, DateTimeKind.Utc).AddTicks(8235),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("KR5.Models.ProductMaterial", b =>
                {
                    b.HasOne("KR5.Models.Material", "Material")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KR5.Models.Product", "Product")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KR5.Models.WorkOrder", b =>
                {
                    b.HasOne("KR5.Models.Product", "Product")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KR5.Models.ProductionLine", "ProductionLine")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProductionLineId");

                    b.Navigation("Product");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("KR5.Models.Material", b =>
                {
                    b.Navigation("ProductMaterials");
                });

            modelBuilder.Entity("KR5.Models.Product", b =>
                {
                    b.Navigation("ProductMaterials");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("KR5.Models.ProductionLine", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
